"""Initial migration

Revision ID: 1a94a54b998d
Revises: 
Create Date: 2024-07-08 15:52:47.226725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a94a54b998d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("additional_info", sa.String(length=511), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("city", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_city_id"), ["id"], unique=False)

    op.create_table(
        "temperature",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("date_time", sa.DateTime(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("temperature", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_temperature_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("temperature", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_temperature_id"))

    op.drop_table("temperature")
    with op.batch_alter_table("city", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_city_id"))

    op.drop_table("city")
    # ### end Alembic commands ###
